locust = locustfile.py

host = ""

#config do tests
users = 1000
spawn-rate = 10
run-time = 120s

headless = true
only-summary = true

csv = locust/locust_report/locustreport
html = locust/locust_report/locustreport.html